### ISSUE TITLE
[Bug] working on Blazor Server RenderMode.InteractiveServer

### ISSUE THREAD

**Issue by Trinita75** [Blazored/Modal#543] opened 2023-11-30 10:38 UTC
Is it possible to work on Blazor Server and RenderMode.InteractiveServer?

CascadingParameter IModalService ModalService
is initially valued correctly
then calling a function

<button @onclick="ShowModal">Test Modal</button>

  public void ShowModal()
  {
      ModalService.Show<Confirm>("Welcome to Blazored Modal");
  }

ModalService is always null

I think this behavior has to do with what is described here
https://learn.microsoft.com/en-US/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-8.0

Thanks

**Comment by antonioatom** [comment] 2023-12-05 18:03
I'm having the same issue. I'm new to blazor so I might be doing something wrong.
I have a page with the BlazoredModal and blazor server with InteractiveServer render mode.

My code is as follows:

```
... (html)
 <button type="button" class="list-group-item list-group-item-action" @onclick="() => ShowModal(variableWithUserEmail)" aria-current="true">
     <i class="bi bi-plus"></i> Add Role...
 </button>

@code {
    [Parameter]
    public int userId { get; set; }

    [CascadingParameter] public IModalService Modal { get; set; } = default!;

    protected override async Task OnInitializedAsync()
    {
        ...
    }

    private void ShowModal(string userEmail)
    {
        var parameters = new ModalParameters().Add(nameof(UserDetailsAddRole.UserEmail), userEmail);
        /// Modal is null here
        Modal.Show<UserDetailsAddRole>("Add Role to User", parameters);
    }
}
```

I have the UserDetailsAddRole component setup as well..

I've followed the getting started guide so:

I'm doing `builder.Services.AddBlazoredModal();` in `Program.cs`

This is my Routes.razor file:
```
<CascadingBlazoredModal>
    <Router AppAssembly="@typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)">
                <NotAuthorized>
                    <RedirectToLogin />
                </NotAuthorized>
            </AuthorizeRouteView>
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
    </Router>
</CascadingBlazoredModal>
```

I don't know what I'm missing. This project is almost the default project from blazor web app created with VS 2022 for .net 8.0 with individual accounts setup, so I'm assuming no weird stuff is going on with custom code.

**Comment by Trinita75** [comment] 2023-12-06 08:00
If you try this, it works

 private IModalService? _modal { get; set; }
 [Inject]
 public IModalService? ModalService
 {
     get { return _modal; }
     set
     {
         if (value is not null)
         {
             value.Show<Confirm>("my modal");
             _modal = value;
         }
     }
 }

from here 

https://learn.microsoft.com/en-US/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-8.0

Cascading parameters don't pass data across render mode boundaries:

Interactive sessions run in a different context than the pages that use static server-side rendering (static SSR). There's no requirement that the server producing the page is even the same machine that hosts some later Interactive Server session, including for WebAssembly components where the server is a different machine to the client. The benefit of static server-side rendering (static SSR) is to gain the full performance of pure stateless HTML rendering.

So is it possible to make blazoredmodal work in blazor server with InteractiveServer rendering mode?

**Comment by tesar-tech** [comment] 2023-12-09 19:59
The problem is this:
You place your CascadingBlazoredModal  in `App.razor`, that is SSR, not interactivity there. The interactivity is enforced on a page. So the cascading parameter is created in different context (ssr) then the context you are trying to use it in (interactivity).

The boundaries are in MainLayout where `@Body` is used...

Your solution can be:

```razor
<CascadingBlazoredModal @rendermode="InteractiveServer">
```

But that means all of the pages will have to be interactive, so no SSR advantages anywhere.

**Comment by mammadkoma** [comment] 2024-01-17 21:15
Is possible using this package without any interactivity and only ssr?

**Comment by chrissainty** [comment] 2024-02-10 00:22
@mammadkoma No, this package needs interactivity to work.

@tesar-tech explanation is correct. If you inject `IModalService` directly into components and omit the `CascadingBlazoredModal` component you can achieve per page functionality. 

I'm going to close this as there isn't an issue with the package. Looks to be the learning curve for .NET 8 and the new render modes.

**Closed by chrissainty** 2024-02-10 00:22 UTC
Labels: Bug, Triage

**Comment by zkkzkk32312** [comment] 2024-11-29 19:59
shouldn't the content in this thread be documented for .NET 8 usage?
