### ISSUE TITLE
[Feature Request] Make the Modal Top Center-able

### ISSUE THREAD

**Issue by Karamethien** [Blazored/Modal#177] opened 2020-06-18 21:41 UTC
Currently, the default positions enum have Top Left, Top Right, but it does not have Top Center.

**Comment by pablopioli** [comment] 2020-06-22 23:49
I build a pull request to implement custom position via CSS.
https://github.com/Blazored/Modal/pull/180

This would accomplish what you want here.

**Comment by chrissainty** [comment] 2020-06-27 11:37
I'm going to close this issue as its actually a duplicate of #146

**Closed by chrissainty** 2020-06-27 11:37 UTC
Labels: Feature Request, Resolved: Duplicate
