### ISSUE TITLE
Modal popup causes horizontal shift when vertical scroll bar exists

### ISSUE THREAD

**Issue by calnastic0** [Blazored/Modal#489] opened 2023-01-13 21:18 UTC
When there is a vertical scroll bar on the page, the Show action of the modal will make the scroll bar be gone, causing the page extend a bit. And when the modal is closed, the re-appearance of the scroll bar will shrink the screen a bit.

Not a functional problem, but would be a nice improvement for user experience.

I tried to post an example but the HTML part would be rendered by the github page. Basically you can just use 30 line breaks to create a scroll bar, and add some content on the right side of the page, then show the modal to see the contents shift.

**Comment by chrissainty** [comment] 2023-01-14 22:51
Hi @calnastic0, this behaviour is by design. We've taken the same approach as Bootstrap do and remove the scroll from the body element in order for the modal content to be scrollable. This isn't something that we will change, but you can obviously make modifications in your applications CSS to adjust this behaviour to your preference.

**Comment by chrissainty** [comment] 2023-01-14 23:18
A fix for this has been submitted, PR #475

**Closed** 2023-10-02 21:09 UTC
Labels: Bug
