### ISSUE TITLE
Microsoft.JSInterop.JSException: 'Could not find 'BlazoredModal' in 'window'. [Bug]

### ISSUE THREAD

**Issue by frablaser** [Blazored/Modal#197] opened 2020-07-16 17:23 UTC
**Describe the bug**
I'm pretty new with the webpack.config, but it seems not injecting blazored.modal.js as it should do...

**To Reproduce**
1- Started the Samples/BlazorServer project
2- Client the Show Modal button on the index page...
3- Get error: Microsoft.JSInterop.JSException: 'Could not find 'BlazoredModal' in 'window'.

**Expected behavior**
It seems that the BlazoredModal.activateScrollLock function is never injected in the _Host.cshtml page in the `<script src="_content/Blazored.Modal/blazored.modal.js"></script>` tag.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**

**Comment by larsk2009** [comment] 2020-07-16 18:26
Sounds related to #196, maybe the suggestions there can also solve your problem?

**Comment by frablaser** [comment] 2020-07-16 18:40
> 
> 
> Sounds related to #196, maybe the suggestions there can also solve your problem?

Thanks Lars, it looks to be the same, I used the solution downloaded directly from github, and I cleared my cache and I tried into other browsers as Google Chrome, Fire Fox,  and the New Ms Edge (based on a mozilla core) and all give the same error...

**Comment by jimnkey** [comment] 2020-07-17 05:23
I was getting a similar error... but only on IE 11.  

blazored.modal.js (in 5.0.1) has a declaration of 'class a' which is not supported in IE -- results in a syntax error.
That in turn causes the error - "... Could not find 'BlazoredModal'..."

What I ended up doing was taking the contents of blazored.modal.js and converting to compatible js with Babel -- and Loading that js only for IE -- seems to work for now.  Got the idea/solution from [here](https://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript)

**Comment by kaysho** [comment] 2020-07-17 09:41
Having the same issues, tried all the suggestions.

**Comment by chrissainty** [comment] 2020-07-17 09:45
@kaysho This has always ended up being a browser caching issue of some kind or another. Unless you're missing the link to the JS file of course 😉.

At this point, the only way we can do something is if someone can provide us with a reliable repro of the problem as I can't recreate it at all.

**Comment by kaysho** [comment] 2020-07-17 12:01
@chrissainty sure, i will try to reproduce it and get in touch.

**Comment by frablaser** [comment] 2020-07-17 17:35
Here is the video of the whole process...

[https://www.screencast.com/t/j55n1JKr7](https://www.screencast.com/t/j55n1JKr7)

**Comment by chrissainty** [comment] 2020-07-17 18:04
@frablaser sorry I completely missed you were trying to run the code in the repo, I thought you were using the NuGet package. 

Based on the error you're seeing in VS, I would guess you don't have NPM installed.

**Comment by frablaser** [comment] 2020-07-17 18:48
> 
> 
> @frablaser sorry I completely missed you were trying to run the code in the repo, I thought you were using the NuGet package.
> 
> Based on the error you're seeing in VS, I would guess you don't have NPM installed.

As you can see in the video, NPMs  returns errors when it pass in the process...  I have to comment it to start the application... 🙄

**Comment by frablaser** [comment] 2020-07-17 18:53
What I need to install to work with NPM? I never used it, I tried NPM install runner, but it don't works...

**Comment by chrissainty** [comment] 2020-07-17 19:13
You need to install NodeJS, NPM is installed along with it.

**Comment by frablaser** [comment] 2020-07-17 19:47
I installed NodeJS and it still ran to an error... 
I'm very new with those things,  What is the node_modules/.install-stamp, run-script build:debug,  run-script build:release? Is that scripts? Can I run it manually? What they are used too? Why it is not directly in the solution? Why always do it complicated instead of no brainier? 😂😂

**Comment by frablaser** [comment] 2020-07-17 19:52
Just for fun, it is supposed to be Javascript free, but I still fighting again java script... 🙄🤭

**Comment by chrissainty** [comment] 2020-07-17 19:59
It's not JavaScript free anymore, if you've spotted anywhere in the repo still saying that can you let me know where. 

Once NPM is installed everything should work automatically. The commands in the csproj file restore the NPM packages, then build the TypeScript. It does this automatically when you build the project.

If you want to try it manually, open a terminal and navigate to the root of the project and then run npm install

**Comment by frablaser** [comment] 2020-07-17 20:04
`    <Description>A JavaScript free modal library for Blazor and Razor Components applications.</Description>`
Here is the mention of JAVA Script free...  😉

**Comment by larsk2009** [comment] 2020-07-18 10:47
Specifically, [here](https://github.com/Blazored/Modal/blob/main/src/Blazored.Modal/Blazored.Modal.csproj#L11)

**Comment by chrissainty** [comment] 2020-07-18 10:50
Thanks @frablaser and @larsk2009. I was sure I'd changed that, but it's turns out I did it in a branch I never merged. 

I'll correct this on the next release.

**Comment by frablaser** [comment] 2020-07-18 15:20
Chriss, 

I still unable to get rid of the npm stuff, even if I installed the NodeJS, npm refuse to work. I spent a whole day to figure out a way to fix it (added $Path in Windows, tried to run directly by Node.exe, etc..), . It's annoying! 

I saw that Blazored.Modal.ts have just a couple of functions into it, could I get the compiled file (debug/release) of it to integrate them directly to my project? I will manage the rest...

Regards...

**Comment by larsk2009** [comment] 2020-07-18 15:22
@frablaser, Is there a reason why you are not using the Nuget package? The Nuget package just uses the javascript file which gets compiled from the *.ts file.

**Comment by chrissainty** [comment] 2020-07-18 15:24
>  Is there a reason why you are not using the Nuget package? The Nuget package just uses the javascript file which gets compiled from the *.ts file.

@larsk2009 you beat me to it 😉

**Comment by frablaser** [comment] 2020-07-18 15:34
> 
> 
> @frablaser, Is there a reason why you are not using the Nuget package? The Nuget package just uses the javascript file which gets compiled from the *.ts file.

I mostly use the source code, as often as possible, sometimes when the things are free code, when comes a new framework (as the next .Net Framework 5), we're stuck with something who is no more updated and maintained.

**Comment by chrissainty** [comment] 2020-07-18 15:38
@frablaser .NET 5 won't have any impact on this library and while I appreciate your concern that a library could become unmaintained, it seems your actions are a bit counter-intuitive. If you'd just used the NuGet package you would have saved yourself a day at least. You could always resort to the source code in the future if the library became stagnant.

As this isn't an issue with the production code we ship and just a local setup issue I'm going to close this issue. Happy to keep helping you with local setup if that's the route you want to take but there isn't any work for us to do here.

**Closed by chrissainty** 2020-07-18 15:38 UTC
Labels: Bug, Triage

**Comment by markoradojkovic** [comment] 2020-11-15 13:19
Hi, you must add script in _host file. like as in image.
![image](https://user-images.githubusercontent.com/56439233/99185991-873fc300-274d-11eb-9e1b-60323e43203a.png)
