### ISSUE TITLE
Modal AutoScrolling when using Bootstrap 5

### ISSUE THREAD

**Issue by danglade** [Blazored/Modal#330] opened 2021-08-10 04:21 UTC
Whenever Bootstrap 5 css is referenced into the project after modal is canceled, it auto-scrolls up and then down.
Does anybody experienced this behavior before?

**Comment by danglade** [comment] 2021-08-10 04:27
Created a test-repo in order to reproduce the issue 

https://github.com/danglade/BlazoredModal-Bootstrap5-issue

**Comment by danglade** [comment] 2021-08-12 23:34
If I remove this line from the actual bootstrap.css on Version v5.0.2 it solves the issue.
But it will be nice to keep the scroll effect bootstrap 5 offers.

**Comment by larsk2009** [comment] 2021-08-13 05:36
hi @danglade,

I can have a look at this hopefully this weekend. If someone hasn't looked into this on monday, please send a reminder 😉.

**Comment by danglade** [comment] 2021-08-16 13:41
Hey @larsk2009 

Hope you had a great weekend, did you have a chance to take a look at this?

**Comment by LongDuongBIT** [comment] 2021-08-28 04:29
Hi @danglade and @larsk2009 ,
I'm experiencing the same problem with Bootstrap 5.
Did you guys find out any solution for it?
Thanks!

**Comment by chrissainty** [comment] 2021-08-31 07:03
At present, we don't support Bootstrap 5 and we haven't tested the library with it.

**Comment by larsk2009** [comment] 2021-09-04 15:52
@danglade well that was a long weekend, sorry for now coming back to you earlier! Seems that the issue is like @chrissainty mentioned. Maybe we can look if it is easy to fix this in the modal, but I cannot give a guarantee if and when we will do that.

**Comment by chrissainty** [comment] 2022-03-09 00:44
This appears resolved with the new focus trap

**Closed by chrissainty** 2022-03-09 00:44 UTC

**Comment by danglade** [comment] 2022-03-09 01:58
@chrissainty: Thanks for letting me know.

**Comment by danglade** [comment] 2022-03-09 15:35
@chrissainty: Just curious, do you know in which version was this fixed?

**Comment by chrissainty** [comment] 2022-03-09 15:36
Yep, its in the v7 preview I published last night

**Comment by danglade** [comment] 2022-03-09 15:41
@chrissainty: Sounds good, will give it a try.
