### ISSUE TITLE
Modal not appearing

### ISSUE THREAD

**Issue by JoHecht** [Blazored/Modal#221] opened 2020-08-24 09:37 UTC
So I know this question already exists but it wasn't helping me.

So here is my Code:

**_Imports.razor**
```
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.JSInterop
@using FHNW_ASS
@using FHNW_ASS.Shared
@using Blazored
@using Blazored.Modal
@using Blazored.Modal.Services
```

MainLayout.razor
```
@inherits LayoutComponentBase
@using FHNW_ASS.Shared; 

<div class="mainContainer">
    <div class="sidebar">
        <NavMenu />
    </div>
    <div class="userProfile">
        <ProfileComponenten />
    </div>



    <div class="content px-4">
        @Body
    </div>
</div>

<BlazoredModal/>
```

**_Host.cshtml**
```
@page "/"
@namespace FHNW_ASS.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FHNW-ASS</title>
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />

    <link href="~/_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />

</head>
<body>
    <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_content/Blazored.Modal/blazored.modal.js"></script>

</body>
</html>
```

**Page with button (Journal.razor)**
```
@page "/Journal"


@using Microsoft.Extensions.Configuration
@using FHNW_ASS.Services

@inject IConfiguration _config
@inject IModalService  modal
@inject IJournalService service


<div class="titleWrapper">
    <div class="title">Journale eine go dreieeee</div>
    <div class="flexbox">
        <div class="content">
            <button @onclick="@(() => modal.Show<JournalInputPage>("Add Journal Entry"))" class="additionButton">
                <img class="plusIcon" src="/elements/plus-black-symbol.svg" />
                Add Journal Entry
            </button>
        </div>
    </div>
</div>
```

**Page that should Pop Up (JournalInputPage.razor)**

```

@using Microsoft.Extensions.Configuration
@using FHNW_ASS.Models


@inject FHNW_ASS.Models.FHNW_ASSContext _context
@inject IConfiguration _config
@inject IModalService  modal

<!DOCTYPE html>

<head>
    <link href="~/css/site.css" rel="stylesheet" />
</head>


<body>
    <EditForm Model="@journalInputModel" OnValidSubmit="HandleValidSubmit">
        <DataAnnotationsValidator />
        <ValidationSummary />

        <p>
            <label for="title">Journal Title</label> <br />
            <InputText id="title" @bind-Value="journalInputModel.JournalTitle" /> <br />
        </p>

        <p>
            <label for="Week">Week</label> <br />
            <InputNumber id="week" @bind-Value="journalInputModel.JournalWeek" /> <br />
        </p>

        <p>
            <label for="content">Journal Content</label> <br />
            @*<InputText id="content" @bind-Value="JournalInput.JournalContent" />*@
            <textarea id="content" rows="10" cols="100" @bind="journalInputModel.JournalContent" />
        </p>

        @*<InputDate id="create" />

            <InputDate id="edit" />*@

        <button type="submit" class="submitButton">Submit</button>
    </EditForm>
</body>






@code {
    

    private JournalInputModel journalInputModel = new JournalInputModel();


    private async void HandleValidSubmit()
    {

        try
        {
            _context.JournalInputModels.Add(journalInputModel);
            await _context.SaveChangesAsync();
        }
        catch
        {
            base.StateHasChanged();
        }
        journalInputModel = new JournalInputModel();
        base.StateHasChanged();
    }


}
```

When I press the button nothing happens and I honestly don't know why

**Comment by chrissainty** [comment] 2020-08-24 10:31
You still have a reference to the modal in your MainLayout. As per the other questions on this subject and as is stated in the readme you must remove this.

I'm going to close this as it's a duplicate of a question which has been resolved a few times now and the answer is no different.

**Closed by chrissainty** 2020-08-24 10:31 UTC
