### ISSUE TITLE
[Bug] Not working in IE11

### ISSUE THREAD

**Issue by jni759** [Blazored/Modal#228] opened 2020-09-03 11:37 UTC
**Describe the bug**
JavaScript error on IE11 using Polyfill latest release (3.0.8) and Blazor.Modal 5.0.3. No modal box shows up and site breaks. 
Project is Blazor Server.

**To Reproduce**
1. Load page
2. Console reports "Syntax Error" blazored.modal.js (1,1114)
3. Activate modal popup
4. New error:

[2020-09-03T11:29:51.226Z] Error: Microsoft.JSInterop.JSException: Could not find 'BlazoredModal' in 'window'.
Error: Could not find 'BlazoredModal' in 'window'.
   at Anonymous function (http://curaswitch.karlshamn.se/_framework/blazor.server.js:8:30742)
   at Anonymous function (http://curaswitch.karlshamn.se/js/blazor.polyfill.min.js:1:4232)
   at Anonymous function (http://curaswitch.karlshamn.se/js/blazor.polyfill.min.js:1:57962)
   at p (http://curaswitch.karlshamn.se/_framework/blazor.server.js:8:30693)
   at Anonymous function (http://curaswitch.karlshamn.se/_framework/blazor.server.js:8:31414)
   at B (http://curaswitch.karlshamn.se/js/blazor.polyfill.min.js:1:85878)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (http://curaswitch.karlshamn.se/_framework/blazor.server.js:8:31384)
   at Anonymous function (http://curaswitch.karlshamn.se/_framework/blazor.server.js:1:19193)
   at Anonymous function (http://curaswitch.karlshamn.se/js/blazor.polyfill.min.js:1:4232)
   at Anonymous function (http://cur

**Expected behavior**
Popup should appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6988301/92110069-69b7ba00-edea-11ea-8f12-b58bcae087df.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
Works of course in other browser (without Polyfill).

**Comment by larsk2009** [comment] 2020-09-03 16:00
I am getting the same errors using the example, even when using version V5.0.0, which I now worked at the time. I will look into this further the coming days.

Also, mental note: If IE11 works again, the readme should be changed. It says now that IE11 is supported from V4.2.0 of Blazored.Modal, which doesn't exist. Support for IE11 was actually released in V5.0.0.

**Comment by larsk2009** [comment] 2020-09-08 16:38
It is obvious that the JS of Blazored.Modal is where it goes wrong in IE11, I just didn't realize that the JS was added after IE11 support was added. I doubt the JS was ever tested in IE11. I'll investigate if I can make the JS work in IE11 as well.

**Comment by larsk2009** [comment] 2020-09-08 16:51
Okay so the problem is most likely that we are generating ES2019 ecmaSript from the TypeScript file, which isn't supported by IE11. We could start generating ES5 ecmaScript to make things work in IE11 again, but I am not sure if this is worth reverting to such a low version. We will also need to change some of the typescript because, for example, the `find` function is not available anymore with the older ecmaScript/TypeScript.

@chrissainty What do you think about this?

**Comment by chrissainty** [comment] 2020-09-17 06:37
Apologies for the delay, I've been away on paternity leave.

So I've had a look at this this morning and I've changed the TypeScript to generate ES2015 which is the same as what the Blazor team generate. But I'm still seeing the error.

Unfortunately the users of IE11 are so small I can't warrant the time to try and fix this. I'm happy to take a PR if someone figures it out however.

**Comment by larsk2009** [comment] 2020-09-17 06:53
Yeah I think ES2015 == ES6, which still won't work in IE11. ES5 should work, but like I said then some other stuff breaks, so I agree it isn't worth the hassle.

**Comment by chrissainty** [comment] 2020-09-17 06:56
Sorry, I was using ES5 - I pretty much copied the TypeScript config from the ASP.NET Core repo

**Comment by larsk2009** [comment] 2020-09-17 07:01
Ah right, in that case it is even more difficult to solve probably.

**Comment by chris5287** [comment] 2020-11-04 15:48
FYI - I fixed this by setting `"target": "ES5"` in `tsconfig.json`, which stops it generating classes that is not supported in IE11.

**Comment by larsk2009** [comment] 2020-11-05 13:19
That did fix it? I am pretty sure I remember trying that, but breaking a bunch of other stuff in the process. For example, the 'find' function I mentioned in a comment above. Is this not the case?

**Comment by larsk2009** [comment] 2021-01-10 11:34
Hmm, I checked again and it seems like `"target": "ES5"` actually does fix this issue. I guess in that case, we could change to that? It doesn't seem to break anything, and would allow IE11 to keep working? @chrissainty What is your opinion on this? I guess it shouldn't break any existing behavior, as it only changes what kind of JS is generated, not the actual functionality right?

**Comment by chrissainty** [comment] 2021-01-10 11:40
If that fixes it then let's do it. As you said, it only changes whats generated.

**Closed** 2021-01-12 06:45 UTC
Labels: Bug, Help Wanted
