### ISSUE TITLE
[Bug] When a modal is open the UI behind the overlay gets stuck

### ISSUE THREAD

**Issue by neymecc** [Blazored/Modal#315] opened 2021-05-18 15:47 UTC
This video shows it:
https://user-images.githubusercontent.com/31436644/118673740-8a4d6600-b7f9-11eb-9f52-a4a108ebec2f.mp4

The problem are these lines:
https://github.com/Blazored/Modal/blob/main/src/Blazored.Modal/Interop/Blazored.Modal.ts#L19-L23
https://user-images.githubusercontent.com/31436644/118675538-f41a3f80-b7fa-11eb-8d1f-241e65d0d088.png

Changed to this:
https://github.com/neymecc/Modal/commit/956f7c7778cc17121d5bed089f88ee822d8809e6#diff-e0f164803baf33800f0ac9c5b617f8c1a6dc6207b4660e070798402a915119e7

Aftermath:
https://user-images.githubusercontent.com/31436644/118681450-e1563980-b7ff-11eb-80f5-aae136ab6d86.mp4

**Comment by larsk2009** [comment] 2021-05-22 13:51
Hi @neymecc,

I agree that those lines are causing the behavior you see. I am not entirely sure why those lines exist, so I am not sure if we will break anything removing those.

@chrissainty You remember why the width is being set, and if it is a good idea to remove it?

**Comment by chrissainty** [comment] 2021-08-13 07:12
Apologies for now responding to this sooner. I don't remember why those lines are there. @larsk2009 it's probably worth us doing a test to make sure there are no other effects to dropping those lines, then we could get this change made,

**Comment by tesar-tech** [comment] 2022-01-28 18:48
Hello, I also encountered this issue, when my side panel  (which is positioned sticky) flew out of the screen. It is caused by setting new position to `body` element as @neymecc  described. 

My guess: The setting of body position when modal is open has some influence on scrollable content on page. Normally when I scroll to 50 % of page, then open model, then close modal, it is still scrolled to 50 % (correct behavior).
But when I scroll to 50 % (doesn't matter what percentage), open modal, **delete added styles from `body`**, close modal -> the content is scrolled up (0 %)..

**Comment by larsk2009** [comment] 2022-01-28 19:45
Ah, nice find @tesar-tech. That is probably the reason. Still, there might be a way to have the best of both solutions. I don't have much time, but if I do have some left over I'll have a look. If you find it in the meantime, feel free to open a PR!

**Comment by tesar-tech** [comment] 2022-01-28 20:46
Unfortunately, the ultimate correct solution is unknow to me. I am on this some time and didn't figured out (yet). But I have few other findings that could be useful. The whole ceremony with js changing size of `body` element is to keep the page content as is, but disable scrollbar. When you open modal, scrollbar is hidden, so you cannot scroll the page (under the modal). This is probably ok feature, but not "must have" I think. The main purpose for hiding scrollbar on the page is `ContentScrollable` prop. It would probably produce weird results with two scrollbars. And I have to say with  `ContentScrollable`  everything works as expected...

When I need to scroll content inside modal I use Blazored.Modal. When I need just simple dialog, I use my own solution, which doesn't change body size. It is basically copy of Blazored.Modal layout, it scrolls page underneath, but works just fine.

**Comment by larsk2009** [comment] 2022-02-01 08:42
Alright, at least we are certain again why the body width and such is being set. I also don't know a good solution but I'll admit I don't have much time to have a look right now.. If anyone is interested in investigating this, feel free!

**Comment by chrissainty** [comment] 2022-03-09 00:41
This is resolved with the new focus trap component.

**Closed by chrissainty** 2022-03-09 00:41 UTC
Labels: Bug, Help Wanted, Needs: Investigation
