### ISSUE TITLE
Modal don't disappear from screen after close / cancel

### ISSUE THREAD

**Issue by TomaszGrzmilas** [Blazored/Modal#200] opened 2020-07-17 11:49 UTC
I used version 4.1.0 - everything ok.

After update to 5.0.1 dialog (after show) always stay on screen despite running:
BlazoredModal.Close(ModalResult.Ok(true))
BlazoredModal.Cancel()
(awaited or not)

I debug and modal stay in DOM after executing code from DismissInstance:

Runtime.InvokeVoidAsync("BlazoredModal.deactivateFocusTrap", Id);
reference.Dismiss(result);
Modals.Remove(reference);
StateHasChanged();

Unfortunately I can't reproduce error on sample Blazor project, there it works fine.

It stops working on my private project.

Hope someone will provide some more details.

**Comment by chrissainty** [comment] 2020-07-17 12:18
Hi @TomaszGrzmilas, I'm sorry to hear you're having issues. Unfortunately as you can't reproduce it and it works on the sample project, this points to it being a local issue to do with the code in your private project. 

Based on this there isn't really anything we can do so I'm going to close this issue, if you can provide some more information or manage to reproduce the problem please reopen it and we can take a look.

**Closed by chrissainty** 2020-07-17 12:18 UTC
Labels: Bug, Triage

**Comment by TomaszGrzmilas** [comment] 2020-07-17 13:23
> Hi @TomaszGrzmilas, I'm sorry to hear you're having issues. Unfortunately as you can't reproduce it and it works on the sample project, this points to it being a local issue to do with the code in your private project.
> 
> Based on this there isn't really anything we can do so I'm going to close this issue, if you can provide some more information or manage to reproduce the problem please reopen it and we can take a look.

Hi @chrissainty 

I menage to reproduce error, please build and run, then click DIALOG button

https://github.com/TomaszGrzmilas/ModelErrorTest

**Comment by chrissainty** [comment] 2020-07-17 13:53
I see the problem, it's the same as covered in #195. You haven't removed the `<BlazoredModal>` tag from your `MainLayout` component. Remvoe that and everything works as expected.

**Comment by TomaszGrzmilas** [comment] 2020-07-17 13:57
> I see the problem, it's the same as covered in #195. You haven't removed the `<BlazoredModal>` tag from your `MainLayout` component. Remvoe that and everything works as expected.

Sorry, my bad. I will read readme.md more carefully in future.

Thank you for your help !
