### ISSUE TITLE
When loading modal with text, it automatically sets scrollbar to the bottom

### ISSUE THREAD

**Issue by Xinoruma** [Blazored/Modal#277] opened 2021-01-06 13:00 UTC
I'm making a modal with a license agreement in it, but for some reason whenever I press on the button to open the agreement it just sets the scrollbar to the bottom and not at the top. Here is my code for the button: 

**index.razor**
![image](https://user-images.githubusercontent.com/51911931/103771000-40709a00-5027-11eb-9006-15c03fc710d9.png)

**LicenseAgreement.razor**
![image](https://user-images.githubusercontent.com/51911931/103771056-53836a00-5027-11eb-942d-662a8b4f3434.png)
![image](https://user-images.githubusercontent.com/51911931/103771068-5aaa7800-5027-11eb-994d-0ebf425899c3.png)

this is the only css used for the agreement:
![image](https://user-images.githubusercontent.com/51911931/103771107-6c8c1b00-5027-11eb-82ec-7981e0f553e6.png)

This is the result that produces for me:
![image](https://user-images.githubusercontent.com/51911931/103771185-89285300-5027-11eb-9f37-a44a95754060.png)

**Comment by larsk2009** [comment] 2021-01-07 07:38
Hi @Xinoruma

This problem doesn't seem to be happening in the [official sampels](https://blazored.github.io/Modal/scrollablecontent). I also don't see any problems with your code. Could you provide a project to reproduce this issue? That way we can confirm the issue and more easily help you solve it.

I do see you are using `@inject` to get the `IModalService`. We are not doing that anymore, instead you access it via a cascading value in each component: `[CascadingParameter] public IModalService Modal { get; set; }`. Maybe try to see if that fixes your issue first?

**Comment by Xinoruma** [comment] 2021-01-07 07:56
> Hi @Xinoruma
> 
> This problem doesn't seem to be happening in the [official samples](https://blazored.github.io/Modal/scrollablecontent). I also don't see any problems with your code. Could you provide a project to reproduce this issue? That way we can confirm the issue and more easily help you solve it.
> 
> I do see you are using `@inject` to get the `IModalService`. We are not doing that anymore, instead you access it via a cascading value in each component: `[CascadingParameter] public IModalService Modal { get; set; }`. Maybe try to see if that fixes your issue first?

I'll try that out, if it doesn't work, I'll provide a project so you can see it for yourself.

**Comment by Xinoruma** [comment] 2021-01-07 08:03
Sadly enough, it doesn't seem to work, here is a link to the repo: https://github.com/Xinoruma/AgreementModal

**Comment by larsk2009** [comment] 2021-01-08 11:19
I am investigating more as to why this happens in your case, but not with the example modal. But, to fix it quickly, add `FocusFirstElement = false` to your `ModalOptions`. So your Task will become the following:

```csharp
public async Task Agreement()
{
  var options = new ModalOptions { ContentScrollable = true, FocusFirstElement = false };
  
  var messageForm = modal.Show<LicenseAgreement>("License Agreement", options);
  var result = await messageForm.Result;
  if (!result.Cancelled)
  {
    return;
  }
}
```
I'll keep you updated if I find the reason this doesn't happen in the official samples.

**Comment by Xinoruma** [comment] 2021-01-08 12:02
Alright, thanks! it works after I added the FocusFirstElement option

**Comment by chrissainty** [comment] 2021-08-13 07:16
Closing as this looks resolved.

**Closed by chrissainty** 2021-08-13 07:16 UTC
Labels: Bug, Needs: Investigation
