### ISSUE TITLE
[Bug] overly and modal size on iOS 15 safari, iphone

### ISSUE THREAD

**Issue by CrahunGit** [Blazored/Modal#348] opened 2021-10-02 00:25 UTC
**Describe the bug**
With Safari on iOS 15 I can see a gap corresponding to the address bar

**To Reproduce**
1. Open sample site with safari on 15 and launch any modal
2. You’ll see a gap at the end of the footer

**Expected behavior**
Overly and modal must occupy the total height. A gasp must not be there. 

**Screenshots**

![6B6CB616-7135-4668-B1AD-837AA48E3C64](https://user-images.githubusercontent.com/12015993/135697744-e1074e0b-5271-4d41-af95-eb9a17343e5c.jpeg)

**Comment by CrahunGit** [comment] 2021-10-02 07:56
This is another screenshot of my current page. As you can see the content has the gap at the bottom
![204D31D8-7AE3-4841-A5D2-60A149582B26](https://user-images.githubusercontent.com/12015993/135708466-105b86ac-1f93-448b-9302-2e5200ab1345.png)

**Comment by larsk2009** [comment] 2021-10-04 20:05
I just tried this on an iPhone 8 with IOS 14.8 and can't reproduce it there, so I assume this is something specific to IOS15 (and/or the safari version shipped with that)? Do you have any way or tools to figure out what is causing this? I don't think I can easily debug this as I don't have an IOS15 device. Maybe @chrissainty does.

**Comment by CrahunGit** [comment] 2021-10-04 20:06
Just my phone but no way to debug it. Sorry. Yes, it’s specific to iOS 15 on iPhone. On iPad works as expected.

**Comment by larsk2009** [comment] 2021-10-04 20:12
Hmm that is strange. I see there might be some tools to have something like the chrome element inspector in safari, maybe have a look if that works and if you can see the problem with that?

**Comment by CrahunGit** [comment] 2021-10-04 20:14
Safari on iOS 15 has the address bar at the bottom. When bar is full size bug does not happened. Just When it’s collapsed. It must be any calc for the overly.

**Comment by Carmenrosacoder** [comment] 2021-11-25 20:17
Hola, hallaron una solución ? tengo el mismo problema :/ con la actualización a ios 15

**Comment by larsk2009** [comment] 2021-12-03 10:32
I found out there is actually a way to debug in safari on iOS using windows PC, maybe you guys can try that to figure out what is going wrong? See [this link](https://washamdev.com/debug-a-website-in-ios-safari-on-windows/) as a starting point. I recently did this at work and it helped me solve a iOS/safari specific bug

**Comment by Carmenrosacoder** [comment] 2021-12-03 14:16
Actually debug my ios device on Windows PC: D, but didn't find the problem: c Then I was able to solve by adding height: 100vh in html. Thanks @larsk2009

**Comment by larsk2009** [comment] 2021-12-03 20:29
Great that it is solved. If you happen to figure out what causes it and we can fix it, don't hesitate to re-open this issue.

**Comment by larsk2009** [comment] 2021-12-07 07:18
So my work phone just updated to iOS 15 and I am getting this exact same issue, so I am reopening this issue

**Comment by DimkaSklyar** [comment] 2022-02-01 09:10
There was the same problem with the modal window on the angular project. When opening the modal window, styles were added to the html tag:

```
.myClass {
 position: fixed;
 width: 100%;
 overflow-y: scroll;
}
```

Apparently `position fixed;` can't calculate the height correctly.

I applied the following styles to the html tag, after opening the modal window, and everything became fine.

```
@media (max-width: 620px)
.myClass {
    position: static !important;
    overflow: hidden;
}
```

I hope this helps you.

P.S.: Apologize for my English ^__^

**Comment by Carmenrosacoder** [comment] 2022-02-04 15:15
In my case, it didn't work that way 😢  , but I was able to solve it with the height 100vh on mobile, thanks @DimkaSklyar .

My English is not good either 🙃

**Comment by chrissainty** [comment] 2022-07-09 11:38
I've just been checking this and it appears to not be an issues anymore, at least I can't recreate the scenarios described here. This could have been down to the focus trap and now it's been reworked, the issue has been cleared up.

I'm going to close this as fixed, but if anyone can produce a repro for it, please reopen and I'll look at it again.

**Closed by chrissainty** 2022-07-09 11:38 UTC
Labels: Bug, Needs: Investigation
