### ISSUE TITLE
[Bug] Modal with `UseCustomLayout = true` option doesn't close/cancel on click outside

### ISSUE THREAD

**Issue by AndreiGorlov** [Blazored/Modal#265] opened 2020-11-25 11:59 UTC
**To Reproduce**
1. Run sample project
2. Click on "Custom Layout"
3. Click on "Show Modal"
4. Click outside modal

**Expected behavior**
Modal expected to be dissmised

**Comment by chrissainty** [comment] 2020-11-25 12:09
This behaviour is by design. When you choose UseCustomLayout, you're expected to provide the full implementation of the layout. 

If you want a background click to close the modal you must add an onclick handler somewhere in your markup which calls ModalInstance.Close.

**Comment by AndreiGorlov** [comment] 2020-11-25 12:16
There is **<div class="modal-backdrop fade show" @onclick="Cancel"></div>** in samples BlazorWebAssembly/Shared/CustomBootstrapModal.razor but it doesn't work.

**Comment by chrissainty** [comment] 2020-11-25 12:35
Ah, thanks for spotting that!

The functionality is working it was just that the onclick handler was on the wrong element. I've just pushed the fix for the sample.

**Closed** 2020-11-25 12:35 UTC
Labels: Bug, Resolved: By Design

**Comment by AndreiGorlov** [comment] 2020-11-25 12:40
But now modal closing on click **inside** also...

**Comment by chrissainty** [comment] 2020-11-25 12:47
Yes, I shouldn't do things when I'm in a hurry. That sample will need to change as the way bootstrap structures the modal will make a background close click very difficult.

**Comment by chrissainty** [comment] 2020-11-25 12:56
@AndreiGorlov I've raised #266 to address fixing the sample.
