### ISSUE TITLE
Bootstrap 4 classes

### ISSUE THREAD

**Issue by georgeemr** [Blazored/Modal#284] opened 2021-01-16 05:25 UTC
Should be great to use the bootstrap 4 default modal classes so they can match the design

**Comment by larsk2009** [comment] 2021-01-17 10:01
Can you explain a little more what you mean by this? Maybe you can give an example of the change you would like?

**Comment by georgeemr** [comment] 2021-01-25 02:45
Sure, it's because my design conflicts with the overlay of the component because the original overlay element is inserted outside the modal code and in this case is inserted inside the modal code container and this is causing the overlay not to overlay my menu.

For example:
![image](https://user-images.githubusercontent.com/3822009/105654956-b9c01780-5e84-11eb-95d7-adae62abee7a.png)

If I put the overlay outside of the blazored-modal-container element like the original bootstrap 4 modal it works.
![image](https://user-images.githubusercontent.com/3822009/105655022-e2481180-5e84-11eb-9e2f-c329d36e5141.png)

![image](https://user-images.githubusercontent.com/3822009/105655037-eaa04c80-5e84-11eb-8b99-6376611bd667.png)

I'm trying to implement the custom layout to use the standard bootstrap 4 modal but I'm unable to do successfully do it.

**Comment by georgeemr** [comment] 2021-01-25 02:46
If you can show me an example to implement the custom layout I think I can fix it.

**Comment by georgeemr** [comment] 2021-01-25 03:11
As I understand from the custom bootstrap modal example, I need to replace all my code with that component and I think I will need to send a custom parameter to set what component i'm loading inside that component. Is this correct?

![image](https://user-images.githubusercontent.com/3822009/105656846-bf1f6100-5e88-11eb-82a0-dc91c4525919.png)

**Comment by chrissainty** [comment] 2021-01-25 07:46
Don't we have an example of this in the samples? Isn't the [Custom Layout](https://blazored.github.io/Modal/customlayout) using Bootstrap 4 classes?

**Comment by chrissainty** [comment] 2021-01-25 07:51
@georgeemr That sounds about right. I would try and encapsulate all of the Bootstrap markup in a component and then you can just declare that one each component to be displayed instead of having a huge if else statement as you add more and more components to be displayed.

**Comment by georgeemr** [comment] 2021-01-25 16:40
Thanks a lot @chrissainty . I appreciate your effort.
At the momento I finally end with this implementation:

![image](https://user-images.githubusercontent.com/3822009/105735201-0a715800-5ef9-11eb-9b07-ea5b105effd5.png)
![image](https://user-images.githubusercontent.com/3822009/105735279-21b04580-5ef9-11eb-9f2e-6b3bb2b65085.png)

If this implementation can end with something like:
var modalOptions = new ModalOptions();
modalParameters.BootstrapLayout = true;
var modalParameters = new ModalParameters();
modalParameters.Add("Item",value);
Modal.Show<MyOriginalComponent>("My title", modalParameters, modalOptions);

Thanks a lot for following the issue.

**Comment by hhyyrylainen** [comment] 2021-04-11 15:30
I'm working on a blazor WASM app that I setup from the official sample project, which comes with bootstrap 4, so it'd be nice if there was an easy way for this modal system to use the bootstrap modal styling. https://getbootstrap.com/docs/4.4/components/modal/

**Comment by chrissainty** [comment] 2021-04-17 07:15
We have an [example](https://blazored.github.io/Modal/customlayout) of how to do this in the sample projects.

**Comment by hhyyrylainen** [comment] 2021-04-17 07:44
I saw that example, but when I do the exact code shown by that page, the layout just breaks entirely. So how do I setup it to use the bootstrap style correctly? It seems that the modal content just gets dumped without a container to the start of the app div.

**Comment by hhyyrylainen** [comment] 2021-04-17 08:14
Okay so I got this working, but I had to inspect the example closely, because the instructions are very incomplete. So in addition to specifying the `UseCustomLayout` property, you need to make all of your modals based on this code: https://github.com/Blazored/Modal/blob/main/samples/BlazorWebAssembly/Shared/CustomBootstrapModal.razor which I wrapped into a new component so I don't have to copy paste all the bootstrap stuff for each modal type. Which results in almost perfect modal actions, it just seems to hide the side top bar and left navigation bar gets pushed up.

**Comment by chrissainty** [comment] 2021-04-17 09:35
What am I looking for in the images you've posted @hhyyrylainen? Sorry I can't spot what you're referring to.

**Comment by hhyyrylainen** [comment] 2021-04-17 09:38
Compare the bottoms of the images. When the modal is open, the left sidebar box is pushed up leaving some white space visible underneath it. And also the top is cutoff, even though the sidebar uses the css sticky style.

**Comment by chrissainty** [comment] 2021-04-17 12:37
Ah, ok I see. @larsk2009 you got any ideas on this one?

**Comment by larsk2009** [comment] 2021-04-19 17:36
I don't seem to be able to reproduce this, but that is probably just me. @hhyyrylainen can you provide a repo which reproduces this issue? That is the easiest way for us to see the issue and fix it.

**Comment by hhyyrylainen** [comment] 2021-04-19 17:38
@larsk2009 yes, I'm working on this branch in this repo: https://github.com/Revolutionary-Games/ThriveDevCenter/tree/blazor

**Comment by larsk2009** [comment] 2021-04-19 17:43
Thanks. Which project should I run to see the issue you are having?

**Comment by hhyyrylainen** [comment] 2021-04-19 17:46
Yeah, that's a bit complicated. There's no way to currently run it in a minimal sense (see my update to my comment above). But basically running the Server project (once everything is configured) with `dotnet watch` is what runs the app. And even then you'd need to follow the instructions to create an account in the app and create some stuff before being able to see the problem.

**Comment by larsk2009** [comment] 2021-04-19 17:47
Yeah I think it might be better if you create a new issue and make a reproduction that is easy to run, then I would be happy to help you!

**Comment by larsk2009** [comment] 2021-04-19 17:51
As I think the original issue by @georgeemr has been solved, I will close this issue. If it hasn't, please re-open it!.

**Closed by larsk2009** 2021-04-19 17:51 UTC
Labels: Feature Request, Needs: More Information

**Comment by hhyyrylainen** [comment] 2021-04-19 17:57
@larsk2009 opened a new issue: https://github.com/Blazored/Modal/issues/306
BTW this issue was about using the bootstrap classes, which didn't get solved by my latest comments.

**Comment by larsk2009** [comment] 2021-04-19 18:09
@chrissainty something in my head about talking about the thing mentioned by @hhyyrylainen before, but I can't find the issue. What is your opinion about it?

**Comment by chrissainty** [comment] 2021-04-24 08:45
@hhyyrylainen We won't be able to use Bootstrap classes with the modal as that would also require the same structured HTML and we can't guarantee that. The best we can do is provide our own implementation of the Bootstrap styles. This is what larger component vendors such as Telerik do. However, right now I don't have the capacity for this, so if this is something you'd like, we'd be happy to accept a PR. Otherwise this will be added in when there is some capacity. Sorry I can't give a better timeframe right now.

**Comment by hhyyrylainen** [comment] 2021-04-24 17:16
@chrissainty I got things working on my app by doing the following:
- `UseCustomLayout = true`
- Created a new helper component that does the bootstrap style: https://github.com/Revolutionary-Games/ThriveDevCenter/blob/5c8c148832a5f7399ca7c346fb440a3675a4f54e/Client/Shared/BootstrapModal.razor#L1
- And then do my modal components by using that helper component as the wrapper: https://github.com/Revolutionary-Games/ThriveDevCenter/blob/fbbaee74bd969ab7b4285ffdb3dcce991f3df378/Client/Shared/ConfirmDelete.razor#L1

So the bootstrap style is now working for me, but for future users it would be much more user friendly if:
- That bootstrap helper component was contained in this library (instead of just being in the examples, as that's where I found out that I need to do this)
- There was documentation on how to use the bootstrap helper component, as right now the example site / tutorial says that `UseCustomLayout` is required. It doesn't go into more details. So the example is pretty useless at giving people info on how it actually needs to be done so that it works.
