### ISSUE TITLE
Blazor opening double modal popup 

### ISSUE THREAD

**Issue by kamalhms** [Blazored/Modal#225] opened 2020-09-01 05:28 UTC
While i click on this link 2  Modal pop up will appear what is the problem can solve it ?

<a @onclick="@(()=>ShowModal(pd.StudentId))" > <i title="document" class="glyphicon glyphicon-paperclip"></i> 
@code
protected async Task ShowModal(int st)
        {
            var parameters = new ModalParameters();
            parameters.Add(nameof(Downloadfile.StudentId), st);
            var options = new ModalOptions()
            {
                DisableBackgroundCancel = true,
                Animation = ModalAnimation.FadeInOut(1),
               
                
            };
            //  Modal.OnClose += ModalClosed;
            Modal.Show<Downloadfile>("File To Be Download",parameters,options);
        }

**Comment by chrissainty** [comment] 2020-09-01 19:13
Based on the code you've provided I'm not sure. Nothing in that code should display multiple modals. Does the component you're loading in the modal display another modal?

**Comment by Asherslab** [comment] 2020-09-03 01:37
Getting the same issue, only happens after going from 4.1.0 to 5.0.0
I've checked and my code is not calling the open/show method twice or anything
attempted with an extremely simple component just saying "test", duplicated the component twice.

<img width="293" alt="Screen Shot 2020-09-03 at 11 35 50 am" src="https://user-images.githubusercontent.com/28527281/92061466-ba72e700-edd9-11ea-9112-65a33f2d0234.png">
<img width="807" alt="Screen Shot 2020-09-03 at 11 35 55 am" src="https://user-images.githubusercontent.com/28527281/92061467-bc3caa80-edd9-11ea-9347-2bc3789253eb.png">
<img width="412" alt="Screen Shot 2020-09-03 at 11 36 25 am" src="https://user-images.githubusercontent.com/28527281/92061470-bd6dd780-edd9-11ea-9b79-9e7caffde7de.png">

running Blazor WASM 3.2.0 on netstandard2.1, i have the JS/CSS/Cascading all put in correctly.

**Comment by Asherslab** [comment] 2020-09-03 02:13
Figured it out!
remove 
```
<BlazoredModal/>
```
from your layout file

**Comment by chrissainty** [comment] 2020-09-03 05:40
Thanks @Asherslab for pointing that out, its probably the most common issue for people moving from 4.x to 5.

Closing this as it's another duplicate of #195

**Closed by chrissainty** 2020-09-03 05:40 UTC

**Comment by c-l-i-n-t** [comment] 2021-08-13 05:44
This issue also occurs when `<MudDialogProvider />` is defined in multiple files. e.g. in Layout and app.razor.

**Comment by chrissainty** [comment] 2021-08-13 07:02
I'm not sure what `MudDialogProvider` has to do with this as its a different library?

**Comment by scottyboiler** [comment] 2021-09-22 19:23
> Figured it out!
> remove
> 
> ```
> <BlazoredModal/>
> ```
> 
> from your layout file

Thank you!

**Comment by abdulrahmanbasha** [comment] 2022-01-09 12:36
> 

Thank you very much this helped.
