### ISSUE TITLE
[Bug] Left sidebar leaves gab when modal is open

### ISSUE THREAD

**Issue by hhyyrylainen** [Blazored/Modal#306] opened 2021-04-19 17:56 UTC
**Describe the bug**
When a modal is open the left sidebar and the top bar (both that are sticky) don't position themselves correctly.

**To Reproduce**
1. I created a reproduction case based on the WASM sample, repo here: https://github.com/hhyyrylainen/Modal (here's what I changed: https://github.com/hhyyrylainen/Modal/commit/50055e22b5d7fc49232ba98bca3ce0f5ac0e0158)
2. `dotnet run` in `samples/BlazorWebAssembly`
3. Open browser to http://localhost:5000/
4. Scroll down a bit so that the "Show Modal" button is visible but the page is scrolled down at least a little bit
5. Click on the "Show Modal" and pay attention to the bottom left. Now close the modal. See how the left side bar jumps around

update: I just tested with chrome, and noticed that this only happens with Firefox.
Tested versions:
Google Chrome 90.0.4430.72
Mozilla Firefox 87.0

**Expected behavior**
I expect modals opening not messing with the site navigation bar.

**Screenshots**
Modal is open:
![Kuvakaappaus - 2021-04-19 20-51-01](https://user-images.githubusercontent.com/3796411/115281294-83c3c400-a151-11eb-967e-6a05b659354a.png)
Then literally the only thing I do is click the modal X to close it (notice all the other changes that happened on the page):
![Kuvakaappaus - 2021-04-19 20-51-09](https://user-images.githubusercontent.com/3796411/115281351-92aa7680-a151-11eb-859c-a92873b14438.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
- Blazor WebAssembly

**Additional context**
Happens both with the default and bootstrap themes.

**Comment by larsk2009** [comment] 2021-04-19 18:17
Ah the update you mentioned in the issue seems to be why I couldn't reproduce it, I was using chrome. I can see why it happens.

It happens because of [this line](https://github.com/Blazored/Modal/blob/main/src/Blazored.Modal/Interop/Blazored.Modal.ts#L23). Not sure why it only happens in Firefox and if it is a bug in Firefox or by design.

**Comment by chrissainty** [comment] 2021-08-13 07:13
This is linked to #315

**Comment by chrissainty** [comment] 2022-03-09 00:36
This now appears to be fixed with the changes to the focus trap

**Closed by chrissainty** 2022-03-09 00:36 UTC
Labels: Bug
