### ISSUE TITLE
[Bug] Unable to close modal by instantiating code

### ISSUE THREAD

**Issue by rgamage** [Blazored/Modal#219] opened 2020-08-20 00:35 UTC
It appears that the IModalReference.Close() method doesn't work when trying to close a modal that you just created.

In other words, in this example I want to show a modal while some data is loading.  When complete, I want to close the modal.  The modal content is 'dumb', it just displays a loading spinner.

```
        var loadingModal = Modal.Show<LoadingData>("Loading data...");
        var logs = ModuleInfoService.GetModuleLogs(DeviceId, moduleId);
        loadingModal.Close();

```
Am I doing this wrong, or is it really true that you can only close a modal from *inside* the modal instance itself?  That seems really strange to me.  The modal doesn't know when my task is complete, and neither does the user.  May be the same issue here:

[Issue 117](https://github.com/Blazored/Modal/issues/117)

If this is not possible, then why does this Close() method exist?  If this is 'by design' as stated in issue 117, what was the thinking here?  Is it not conceivable we might want to show a message to the user, and then decide when to close it?

Thanks,
Randy

**Comment by larsk2009** [comment] 2020-08-20 04:10
[This](https://www.github.com/Blazored/Modal/tree/main/samples%2FBlazorServer%2FPages%2FLongRunningTask.razor) seems exactly like what you want to do. Have a look at that example and see if it works for you.

**Comment by rgamage** [comment] 2020-08-20 04:27
I’m pretty sure that won’t work, as it’s the same method I’m using in my
code. Is it possible something changed in Blazored Modal that broke this
functionality?

Randy

**Comment by larsk2009** [comment] 2020-08-20 05:04
If you look at [this](https://blazored.github.io/Modal/longrunningtask) page, you can see that sample page in action. There it does work, but maybe you have a different situation where it doesn't work. Could you make a small repository/project you can share with us, which shows this problem? That way we can better see what the problem is.

**Comment by chrissainty** [comment] 2020-09-17 07:18
As there has been no further communication on this issue I'm going to close it.

**Closed by chrissainty** 2020-09-17 07:18 UTC
Labels: Bug, Triage
