### ISSUE TITLE
Uncaught exception when JavaScript code executes

### ISSUE THREAD

**Issue by ThomasPrioul** [Blazored/Modal#323] opened 2021-06-25 10:16 UTC
Environment : Blazored.Modal 6.0.1, .NET core 3.1, server-side Blazor.

The problem :
I'm creating a modal from a timer in a server-side Blazor app (not WASM) to mimic a "Netflix" kind of activity popup.
It works most of the time, but sometimes it will crash my app. I first I thought this was a problem with the timer trying to create a modal when the client isn't there anymore (and no JavaScript/DOM to use) but it's not. The error is hard to reproduce and mostly happens on my production environment, not my dev PC.
The modal is created at first but then some javascript call fails.
I could only catch the exception in the AppDomain exception handler (AppDomain.CurrentDomain.UnhandledException) with the following :
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazored.Modal.BlazoredModal.Update(ModalReference modalReference)

   // Callback from the timer
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

It seems this TaskCanceled exception can happen randomly when using JSRuntime.InvokeVoidAsync. There are many questions on SO with the same problem and people having to catch javascript exceptions.
I can see in the code that the method is an async void without any try/catch clause so it always falls down to the AppDomain unhandled exception.

https://github.com/Blazored/Modal/blob/4581958a720e92b1dd02a21861c4a6fe3da1b512/src/Blazored.Modal/BlazoredModal.razor.cs#L41

https://github.com/Blazored/Modal/blob/4581958a720e92b1dd02a21861c4a6fe3da1b512/src/Blazored.Modal/BlazoredModal.razor.cs#L113-L118

It would be great if the exception could be caught in the code that creates the modal. Despite trying to englobe all my calls, it still fails because this is an async void kind of event and it's decoupled from the modalService.Show<> call and the exception falls into the AppDomain scope. If I find the time, I'll come with a PR.

https://github.com/Blazored/Modal/blob/4581958a720e92b1dd02a21861c4a6fe3da1b512/src/Blazored.Modal/Services/ModalService.cs#L111-L145

**Comment by larsk2009** [comment] 2021-06-25 11:06
hi @ThomasPrioul,

I'd be interested to know the piece of javascript is causing this exception. If you happen to find that out, let us know.
We could put `try ... catch` around these calls in c#, but then we are catching all JS exceptions, which I am not sure we want to do. I am not saying we don't want to do that, just that I am not sure about it 😉. Maybe @chrissainty can pitch in here as well?

**Comment by ThomasPrioul** [comment] 2021-06-25 11:53
Hi @larsk2009.

I hope catching the exception on the C# side could shed some light on why the JavaScript code fails.
My problem is that it's a hard to reproduce bug. But I'll look into it myself and hope to make a PR.

A quick google search for "blazor taskcanceledexception" gives many results in different projects. It seems the problem is related to the JSRuntime implementation having trouble at random times. Maybe this was fixed in .NET 5...
People seem to say that InvokeVoidAsync should be avoided and that the custom JS functions should always return a value even if it's useless and the C# should be using InvokeAsync instead.
https://stackoverflow.com/a/63262779

**Comment by chrissainty** [comment] 2021-06-26 08:32
Hey @ThomasPrioul ,

I'd be curious to know if this is caused by users navigating to a different page from where the timer is triggered. Is the timer being disposed of correctly when it goes out of scope? It's a common issue that timers aren't cleaned by implementing `IDisposable` and they just continue to run causing these types of issues.

**Comment by ThomasPrioul** [comment] 2021-06-28 08:33
> Is the timer being disposed of correctly when it goes out of scope? It's a common issue that timers aren't cleaned by implementing `IDisposable` and they just continue to run causing these types of issues.

It was the first thing that came to my mind. The service that hosts the Timer is Scoped so its lifetime is tied to the WebSocket connection of Blazor, and the framework does call Dispose and DisposeAsync. I use DisposeAsync.

I just found out I was missing a try/finally clause so maybe something else in my StopAsync method was throwing on rare occasions.
Here is my snippet :
```csharp
public async ValueTask DisposeAsync()
{
    if (!disposed)
    {
        disposed = true;
        logger.LogInformation("Disposing DiagnosticsService (user is out)");

        try
        {
            await StopAsync();
        }
        finally
        {
            inactivityTimer.Elapsed -= InactivityTimerElapsed;
            inactivityTimer.Stop();
            inactivityTimer.Dispose();
        }
    }
}
```

The call to StopAsync does invoke an event that tries updating the UI. Maybe that's preventing the timer from being disposed. I tried adding an exception throw there and it doesn't even show up in the logs. Maybe the framework is swallowing this and it goes unnoticed.

Anyway, I think my point about the async void being "bad" still stands, so I modified the code. It does break every call to Show so the commit seems huge but in reality it's not much. I'll open a PR.

**Closed** 2021-09-16 14:17 UTC
Labels: Bug, Needs: Investigation
