### ISSUE TITLE
Blazor Server Page Scroll

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Modal#354] opened 2021-11-03 19:16 UTC
I am using Blazor Server Project with .NET RC2.

I am noticing that when the Page is very large( with vertical scrolling) and we use Blazored Modal, it feels like a postback is occurring but in fact it is just resetting the scroll position. 
Upon the display of Modal, it resets the scroll position to the top of the page.
and then Blazor finishes its work, it scrolls the page down to the original position.

Git Repo
[https://github.com/nssidhu/BlazoredModalPageScroll](https://github.com/nssidhu/BlazoredModalPageScroll)

2) The modal does not appear unless I put Task.Delay.

1) Scrolling problem : On Index Page Click the submit button to see the scrolling problem.
2) Modal does not Show: Remove the " await Task.Delay(2000); " from Calculate method (line 45), you will see that now the Modal will not show

This problem also occurs in Blazor WebAssembly app.

**Comment by nssidhu** [comment] 2021-11-09 15:58
Any updates ?

**Comment by chrissainty** [comment] 2021-11-09 16:04
Not yet. I'm very busy at the moment and I'll get back with an update as soon as I can.

**Comment by chrissainty** [comment] 2022-03-09 00:38
This appears to be fixed with the swap to the new focus trap

**Closed by chrissainty** 2022-03-09 00:38 UTC
Labels: Bug, Needs: Investigation

**Comment by nssidhu** [comment] 2022-03-13 19:13
Still the Same problem, i created new one and tried it.

**Comment by chrissainty** [comment] 2022-03-13 19:17
@nssidhu Can you provide a repro project for this please? I can't replicate it using v7 preview 1.

**Comment by nssidhu** [comment] 2022-03-14 03:52
Here is the repo. 
https://github.com/nssidhu/BlazoredModalIssue

I am using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0

Note: First Generate the Long List, so that the show dialog button move to the bottom of the list.
Scroll down so that "Show Dialog" button is visible and than click it.
You will notice that Dialog displays as expected, but once it Dialog is dismissed, the page scrolls up and then scrolls to the bottom again, this flickering kind of gives sense of postback/page refresh.

**Comment by oicydwa** [comment] 2022-06-17 19:01
I see this issue was closed, but I'm also experiencing this exact same issue and have no idea where to even start looking into it. I used this library because I don't like making JSInterop work myself.

**Comment by oicydwa** [comment] 2022-06-17 21:10
Alright, so I figured out why mine was doing this, and while I am using blazored, the issue is actually regarding my jsinterop for screen location. When my modal opens, it jumps to listening to that position (which is 0) and then when i close it, it springs from 0 to where I actually was when i opened the modal. Therefore issue is unrelated to blazored-modal

**Comment by oicydwa** [comment] 2022-06-17 21:48
I found the cause of this issue, just unsure how to resolve it. When the modal is opened, seems it stores where you were on the page and returns to that location after it's closed. But in between location is set to top of the page, and causes it to scroll to your previous location from 0.

**Comment by chrissainty** [comment] 2022-06-18 06:36
@oicydwa Which version are you using? The fix for this issue is in the latest preview version.

**Comment by oicydwa** [comment] 2022-06-18 12:29
Ahh perfect. That's good to know. I'm using version 6.0.1. I will give the preview version a try. Thank you!
