### ISSUE TITLE
[Bug] Z-Index on secondy modal opened from the first

### ISSUE THREAD

**Issue by jeffersantoss** [Blazored/Modal#285] opened 2021-01-20 16:36 UTC
**Describe the bug**
When I open the second modal from the first one, the inputs fields become not clickable, maybe something related with the z-index. (On the previous versions of Blazored.Modal this was working well.)

**To Reproduce**
![ff7d9e69-6b8e-4ba5-81be-14a3ea3bb39c](https://user-images.githubusercontent.com/10839497/105204675-353b6500-5b23-11eb-8bbe-e40f91e244a0.gif)

**Expected behavior**
Clickable inputs on the second model.

**Hosting Model:**
 - Blazor Server (dotNet5) (With the last version of Blazored.Modal)

**Comment by larsk2009** [comment] 2021-01-22 10:10
Could you share your project by any chance? I just added an input field to the Samples 2nd Modal, and there they do work. I agree it may very well have something to do with the Z-index. It is easiest if you can provide a project which reproduces the issue, then we can see what the issue is.

**Comment by dallaskeener** [comment] 2021-01-22 16:03
I hope this is along the same lines. I'm using Syncfusion's grid within your (awesome) modal component. I've attached a sample where I try to edit within the grid (dialog mode) and the controls within that editing form can't get focus. I hope this helps - thanks!
[ModalTest.zip](https://github.com/Blazored/Modal/files/5857002/ModalTest.zip)

**Comment by larsk2009** [comment] 2021-01-22 16:36
It sounds very similar to #217, but I thought that had been fixed. 

@dallaskeener The issue with your example is probably this: The syncfusion thingy creates its own modal, but it's HTML is not within the Modal. This causes it to be affected by our FocusTrap. The solution, for now at least, is to either globally set `FocusFirstElement` to `false`, or do it on every call to a modal which uses a syncfusion modal (from the webpage al the way to the modal which displays the synfusion modal you will need to add this, that is why I would prefer to make it global).

@jeffersantoss Have a look at what I suggested to @dallaskeener and see if that works for you. If not, we will investigate further.

**Comment by dallaskeener** [comment] 2021-01-22 16:56
Worked like a charm, thanks! And incredibly fast reply time, which is greatly appreciated!

Dumb follow-up question - how would I set FocusFirstElement = False, globally?

**Comment by larsk2009** [comment] 2021-01-22 18:38
In the sample you send:

App.razor
```razor
<CascadingBlazoredModal FocusFirstElement="false">
    <Router AppAssembly="typeof(Program).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="routeData" DefaultLayout="typeof(MainLayout)" />
        </Found>
        <NotFound>
            <h1>Page not found</h1>
            <p>Sorry, but there's nothing here!</p>
        </NotFound>
    </Router>
</CascadingBlazoredModal>
```

**Comment by dallaskeener** [comment] 2021-01-22 18:41
Thanks so much!

**Comment by jeffersantoss** [comment] 2021-01-26 01:35
> In the sample you send:
> 
> App.razor
> 
> ```
> <CascadingBlazoredModal FocusFirstElement="false">
>     <Router AppAssembly="typeof(Program).Assembly">
>         <Found Context="routeData">
>             <RouteView RouteData="routeData" DefaultLayout="typeof(MainLayout)" />
>         </Found>
>         <NotFound>
>             <h1>Page not found</h1>
>             <p>Sorry, but there's nothing here!</p>
>         </NotFound>
>     </Router>
> </CascadingBlazoredModal>
> ```

Worked like a charm here too as @dallaskeener said 😁! Thank you very much for the solution for this @larsk2009. 
Is this option true by default for some reason?

**Comment by larsk2009** [comment] 2021-01-26 08:18
Yes it is! Normally this works so the 1th element is focused in the Modal. If you are just using the modal 'vanilla', without any other components in it that are doing things like opening their own modals, this works very well. It is very good for accessibility I believe. But in your case, it is obviously not preffered, which is why the option is there.

As it seems everything is solved here, I will close this issue.

**Closed by larsk2009** 2021-01-26 08:18 UTC
Labels: Bug, Triage
